### ISSUE TITLE
Is it possible to add gevent rpyc server&client?

### ISSUE THREAD

**Issue by zhangchunlin** [tomerfiliba/rpyc#146]
Is it possible to add gevent rpyc server&client?
I think gevent is a good style to implement rpyc server&client, I am learning rpyc source code and try, but I think it is better if author can offer some help.

**Comment by coldfix** [comment]
Sorry, I don't have any experience with gevent, but from what I know, it might already work with rpyc, since it yields control on the lower level primitives, right? I'll close for now, but I'm very open to accept patches if my assessment is not or only partially true.
