### ISSUE TITLE
remote popen file object can not read like a stream

### ISSUE THREAD

**Issue by zhangchunlin** [tomerfiliba/rpyc#148]
```
    import rpyc
    c = rpyc.classic.connect("127.0.0.1")
    f = c.modules.os.popen("ping www.google.com -c 3")
    for l in f:
        print l,
```

Above code will print after ping finished,not like a stream when run in local, is it possible to act as local popen file object?

**Comment by coldfix** [comment]
For me, the given example shows the same behaviour both for local/remote execution:

- python2.7 show complete output after finishing all pings
- python3.6 show output line by line on every ping

If you still experience this issue, can you reopen and give more details (platform, python version, example for local code)?

Best, Thomas
