### ISSUE TITLE
Can't access attributes from callback objects with allow_public_attrs and/or allow_all_attrs

### ISSUE THREAD

**Issue by jdmears2** [tomerfiliba/rpyc#154]
I'm pasting in two files: server.py and client.py.  

server.py:

<pre lang="python"><code>
import thread
import rpyc

def run_something(callback):
    for i in xrange(100):
        print dir(callback)
        callback.runCallback()
        #callback(i)
        
    
class CallbackTest(object):
    def __init__(self, callback):
        self.callback = callback
        
    def start(self):
        thread.start_new_thread(run_something, (self.callback,))
                
class MyService(rpyc.Service):
    """
    RPyC service that runs in My and exposes a command processor to external
    applications
    """
            
    def on_connect(self):
        """
        Invoked when the client connects.  Performs required initialization
        """
        print "Executive connected", thread.get_ident()
                
    def on_disconnect(self):
        """
        Invoked when the client disconnects.
        """
        print "Executive has disconnected..."
    
    class exposed_RemoteCallbackTest(CallbackTest):
        def __init__(self, callback):
            CallbackTest.__init__(self, callback)

def go():
    from rpyc.utils.server import ThreadedServer
    myServerObj = ThreadedServer(
        MyService, port=1200, 
        protocol_config={"allow_public_attrs": True, "allow_all_attrs": True})
    print "Waiting for a connection..."
    myServerObj.start()
</code></pre>

client.py
<pre lang="python"><code>
import rpyc
import time
    
def startup(host, port, attempts, retryInterval):
    
    attemptCount = 0
    while True:
        
        try:
            print "Attempting to connect to %s:%d" % (host, port)
            conn = rpyc.connect(host, port)
            break
        except:
            attemptCount += 1
            if attemptCount > attempts:
                raise
                    
        time.sleep(retryInterval)

    print "Connected to %s:%d" % (host, port)
    return conn

class Callback(object):
    def __init__(self):
        self.called = 0
        
    def runCallback(self, val):
        self.called += 1
        print val, time.time()

def go():
    host = "localhost"
    port = 1200
    
    conn = startup(host, port, 5, .1)
    
    rpyc.BgServingThread.SLEEP_INTERVAL = 0
    bgsrv = rpyc.BgServingThread(conn)
    
    c = Callback()
    test = conn.root.RemoteCallbackTest(c)

    print test
   
    test.start()
</code></pre>

After you've copied the text into local copies, open two interpreters and in the first do:

    import server
    server.go()

Then in the second:

    import client
    client.go()

What you'll see is in the interpreter running the server module:

    Unhandled exception in thread started by <function run_something at 0x22ea488>
    ======= Remote traceback =======
    Traceback (most recent call last):
      File "/opt/goes/lib/python2.7/site-packages/rpyc/core/protocol.py", line 300, in _dispatch_request
        res = self._HANDLERS[handler](self, *args)
      File "/opt/goes/lib/python2.7/site-packages/rpyc/core/protocol.py", line 538, in _handle_getattr
        return self._access_attr(oid, name, (), "_rpyc_getattr", "allow_getattr", getattr)
      File "/opt/goes/lib/python2.7/site-packages/rpyc/core/protocol.py", line 501, in _access_attr
        raise AttributeError("cannot access %r" % (name,))
    AttributeError: cannot access 'runCallback'
    
    ======= Local exception ========
    Traceback (most recent call last):
      File "server.py", line 7, in run_something
        callback.runCallback()
      File "/opt/goes/lib/python2.7/site-packages/rpyc/core/netref.py", line 150, in __getattr__
        return syncreq(self, consts.HANDLE_GETATTR, name)
      File "/opt/goes/lib/python2.7/site-packages/rpyc/core/netref.py", line 71, in syncreq
        return conn.sync_request(handler, oid, *args)
      File "/opt/goes/lib/python2.7/site-packages/rpyc/core/protocol.py", line 438, in sync_request
        raise obj
    AttributeError: cannot access 'runCallback'

This despite the fact that allow_all_attrs and allow_public_attrs are set in the server's protocol config.  Below is a working version of these files that tweaks the files ever so slightly.  Instead of passing in a callback object, it passes in a reference to the object's callback method and the server invokes that directly.

server_good.py
<pre lang="python"><code>
import thread
import rpyc

def run_something(callback):
    for i in xrange(100):
        print dir(callback)
        callback(i)
        
    
class CallbackTest(object):
    def __init__(self, callback):
        self.callback = callback
        
    def start(self):
        thread.start_new_thread(run_something, (self.callback,))
                
class MyService(rpyc.Service):
    """
    RPyC service that runs in My and exposes a command processor to external
    applications
    """
            
    def on_connect(self):
        """
        Invoked when the client connects.  Performs required initialization
        """
        print "Executive connected", thread.get_ident()
                
    def on_disconnect(self):
        """
        Invoked when the client disconnects.
        """
        print "Executive has disconnected..."
    
    class exposed_RemoteCallbackTest(CallbackTest):
        def __init__(self, callback):
            CallbackTest.__init__(self, callback)

def go():
    from rpyc.utils.server import ThreadedServer
    myServerObj = ThreadedServer(
        MyService, port=1200, 
        protocol_config={"allow_public_attrs": True, "allow_all_attrs": True})
    print "Waiting for a connection..."
    myServerObj.start()
</pre></code>

client_good.py
<pre lang="python"><code>
import rpyc
import time
    
def startup(host, port, attempts, retryInterval):
    
    attemptCount = 0
    while True:
        
        try:
            print "Attempting to connect to %s:%d" % (host, port)
            conn = rpyc.connect(host, port)
            break
        except:
            attemptCount += 1
            if attemptCount > attempts:
                raise
                    
        time.sleep(retryInterval)

    print "Connected to %s:%d" % (host, port)
    return conn

class Callback(object):
    def __init__(self):
        self.called = 0
        
    def runCallback(self, val):
        self.called += 1
        print val, time.time()

def go():
    host = "localhost"
    port = 1200
    
    conn = startup(host, port, 5, .1)
    
    rpyc.BgServingThread.SLEEP_INTERVAL = 0
    bgsrv = rpyc.BgServingThread(conn)
    
    c = Callback()
    test = conn.root.RemoteCallbackTest(c.runCallback)

    print test
   
    test.start()
</pre></code>

**Comment by tomerfiliba** [comment]
You probably just need to configure allow_all_attrs on the clients side as
well. Tell me how it goes

**Comment by jdmears2** [comment]
Yep, that took care of it.  Change the connect on the client side to:
```conn = rpyc.connect(host, port, config={"allow_all_attrs": True})```
