### ISSUE TITLE
Jython: rpyc Server doesn't report correct listening port when set to 0

### ISSUE THREAD

**Issue by campbellr** [tomerfiliba/rpyc#156]
This seems to just be a quirk in Jython's socket implementation (see [jython issue 1806](http://bugs.jython.org/issue1806)):

``` python
>>> import socket
>>> s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
>>> s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
>>> s.bind(("localhost", 0))
>>> s.settimeout(0.5)
>>> s.getsockname()
('127.0.0.1', 0)
```

But, if we add a call to `s.listen`, the next `s.getsockname()` returns the correct info:

``` python
>>> s.listen(1)
>>> s.getsockname()
('127.0.0.1', 57581)
```

I'm not sure how much you care about Jython suport, but it seems like it would pretty safe to update `self.port` in `Server.start` after calling `listen`.

**Comment by coldfix** [comment]
Thanks! Fix implemented as understood from your description (better late than never). Give me a shout if the problem is not solved.

Best, Thomas
