### ISSUE TITLE
Getting weird python27 error when running rpyc_classic on python33.

### ISSUE THREAD

**Issue by cparrish60** [tomerfiliba/rpyc#161]
I don't even have Python27 installed.
![rpyc error](https://cloud.githubusercontent.com/assets/10676583/6645943/bb7d53dc-c996-11e4-92d7-9d79d0fb92f7.jpg)

**Comment by ya-mouse** [comment]
Try to run:
> C:\python33\python.exe c:\python33\scripts\rpyc_classic.py

**Comment by coldfix** [comment]
Seems like you messed up your python installation / PATH variable, probably unrelated to rpyc. If you still have this problem, please reopen and post the output of `SET` (which is I believe the windows equivalent for the raw `env` command).
