### ISSUE TITLE
on_service_removed() callback gets called for every service registered

### ISSUE THREAD

**Issue by stirlingboy69** [tomerfiliba/rpyc#172]
Hello,

In version 3.3.0 I believe there is a tabbing mistake inside the function _remove_service
(file registry.py line 68). I am thinking the try/except block should be inside the if block (line 73). 

Currently, when the if code removes the service from the list the on_service_remove() gets called.  However, since the try/except block is outside of the if statement the on_service_remove() is invoked for every other service that has been registered.

As quick test, I've moved the try/except block inside the if and that seems to fix the bug I've noticed
in my code whenever a client service is removed.

Thanks.
Pete

**Comment by tomerfiliba** [comment]
could you submit a pull request?

**Comment by stirlingboy69** [comment]
Okay, I'll have to read up on how to submit a pull. Sorry for any delays, I am new to github.
Pete

**Comment by coldfix** [comment]
Was closed by #173.
