### ISSUE TITLE
Problem with some old-style exception raised remotely.

### ISSUE THREAD

**Issue by sergei-dyshel** [tomerfiliba/rpyc#181]
I have a problem with exception defined [here](https://github.com/jparyani/pycapnp/blob/develop/capnp/lib/capnp.pyx#L199).

Though this exception is derived from `Exception` and should new-style, in fact the old-style-specific code is called in `vinegar.py` (look [here](https://github.com/tomerfiliba/rpyc/blob/master/rpyc/core/vinegar.py#L152)). 

According to Python [docs](https://docs.python.org/2/reference/datamodel.html#object.__new__) (see also [this](https://bugs.python.org/issue15542) issue for clarification), the following line in `vinegar.py`

``` python
exc = cls.__new__(cls)
```

creates an instance without calling `__init__()` and then, in case of `KjException`, further call to `setattr()` invokes property functions which expect `wrapper` field (of `KjException`) to be defined. Since `__init__()` was not called, we get an exception here.

**Comment by coldfix** [comment]
Hi, I'm in the process of addressing old issues. Does this issue still occur? Can you give a small example? I assume the link to your code is out of date.

**Comment by sergei-dyshel** [comment]
Honestly I don't remember :smile: I think you can close this by now
