### ISSUE TITLE
wrong description  in readthedocs

### ISSUE THREAD

**Issue by bardlet** [tomerfiliba/rpyc#185]
[http://rpyc.readthedocs.org/en/latest/docs/zerodeploy.html#multiserverdeployment](url)

under MultiServerDeployment chapter：

The original is:

`from plumbum.utils.zerodeploy import MultiServerDeployment`

probably is：

`from rpyc.utils.zerodeploy import MultiServerDeployment`

:)

**Comment by coldfix** [comment]
Thanks, don't hesitate to send PRs even for small typo fixes etc.
