### ISSUE TITLE
Client authentication

### ISSUE THREAD

**Issue by alexsilva** [tomerfiliba/rpyc#189]
The document clearly explains how the server must do to authenticate crendenciais sent by the client, but fails to explain `how the client sends authentication`.

It does not have an api to send authentication data ?

**Comment by alexsilva** [comment]
It was very difficult to understand how the authentication flow works, 
but some have done it in a simple way.

[NorthCat] (https://github.com/NorthCat/test2)

[client](https://github.com/NorthCat/test2/blob/29ac9be93b6fc75ba05fb59c36d5a2538946dc8b/client.py#L13)
[server](https://github.com/NorthCat/test2/blob/29ac9be93b6fc75ba05fb59c36d5a2538946dc8b/server.py#L9)

The reason not be simple should be a native api.

**Comment by coldfix** [comment]
I've added a reference to the corresponding client side function.
