### ISSUE TITLE
zerodeploy - server_class doesn't contain module name - breaks MultiServerDeployment

### ISSUE THREAD

**Issue by jmetz** [tomerfiliba/rpyc#194]
Trying to follow the example on zero deployment using `MultiServerDeployment` (after applying fix mentioned by bardlet in #185), get 

``` shell
  File "/usr/local/lib/python3.4/dist-packages/rpyc/utils/zerodeploy.py", line 102, in __init__
    modname, clsname = server_class.rsplit(".", 1)
ValueError: need more than 1 value to unpack
```

Upon debugging, `server_class` turns out to contain `"ThreadedServer"` - i.e. no module name.

**Comment by coldfix** [comment]
Thanks. The default argument didn't contain the fully qualified class name. You can specify it manually:

```python
dep = MultiServerDeployment([m1, m2, m3], 'rpyc.utils.server.ThreadedServer')
```

Default is fixed on most recent master. Reopen otherwise.

Best, Thomas
