### ISSUE TITLE
Connect to a virtualenv python?

### ISSUE THREAD

**Issue by tgoodlet** [tomerfiliba/rpyc#195]
Is it possible to connect a `Python` interpreter installed in a [`virtualenv`](https://virtualenv.pypa.io/en/stable/)? It would be very useful to hook into multiple envs running different library sets when testing.

**Comment by tgoodlet** [comment]
Ahh just found the `python_executable` kwarg to `zerodeploy.DeployedServer`.
I might send you a PR to document that.

**Comment by coldfix** [comment]
Thanks.
