### ISSUE TITLE
Feature: Expose decorator

### ISSUE THREAD

**Issue by aplicacionamedida** [tomerfiliba/rpyc#200]
I think that its a little bit more pythonic to expose methods in services using decorators instead of using a naming convention.

```python

class XmppService(rpyc.Service):
   @rpyc.expose
   def my_exposed_method(self, param1, param2):
        pass
```

**Comment by petmakris** [comment]
There is some answer in the google group which states that the author of rpyc did not want to go with a decorator as this would not allow to expose classes and class properties.

**Comment by coldfix** [comment]
Note that you can easily make your own decorator for that.
