### ISSUE TITLE
Please create new version

### ISSUE THREAD

**Issue by eplaut** [tomerfiliba/rpyc#214]
Hi!

since `master` is pretty stable (1 year without any commit), can we create new package on pypi? there are ~10 PR merged since last package creation

Many thanks!

**Comment by eplaut** [comment]
@tomerfiliba please consider it

**Comment by tomerfiliba** [comment]
@eplaut - do you want to become the maintainer? i'm looking for someone

**Comment by eplaut** [comment]
@tomerfiliba let's go private. I am willing to donate to the project, but I need more information. 

@gmail.com

**Comment by coldfix** [comment]
Hi,

I've been watching this project for some time and I'd love to see it stay alive. I myself considered submitting one or two PRs but left it alone when I saw that some of the existing PRs and issues haven't been handled in a while.

Unless @eplaut (or someone else) wishes to step in as a maintainer, I would be happy to do it.

Best, Thomas

**Comment by tomerfiliba** [comment]
@coldfix - made you a collaborator. what's your PyPI username?

**Comment by coldfix** [comment]
Great. It's coldfix as well.

**Comment by tomerfiliba** [comment]
done. let me know if anything's wrong

**Comment by coldfix** [comment]
Ok. I'll create and upload a new version before touching any of the issues/PRs next week or so. Is there anything special about the release process, or just the usual `git tag / python setup.py sdist / twine upload`?

**Comment by tomerfiliba** [comment]
i used to do it with `./build.py` -- https://github.com/tomerfiliba/rpyc/blob/master/build.py

but obviously you can do that manually as well

**Comment by henryiii** [comment]
I've had an issue with `build.py` in Plumbum, so I'd recommend checking the script before running it. I think it was written pre-twine.

**Comment by coldfix** [comment]
uploaded new version to pypi

**Comment by eplaut** [comment]
@coldfix @tomerfiliba many thanks!
