### ISSUE TITLE
Streams seem to have a limit to the data that can be passed over at a time

### ISSUE THREAD

**Issue by jrg94** [tomerfiliba/rpyc#217]
I've been running into a bit of a strange issue with the rpyc library, so I'll do my best to explain what is going on. Unfortunately, the application is proprietary, so I can't link any code. However, I can share the error as well as the exact circumstances in which the error occurs.

```
File "C:\Python27\lib\site-packages\rpyc\core\netref.py", line 148, in __getattribute__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "C:\Python27\lib\site-packages\rpyc\core\netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "C:\Python27\lib\site-packages\rpyc\core\protocol.py", line 436, in sync_request
    seq = self._send_request(handler, args)
  File "C:\Python27\lib\site-packages\rpyc\core\protocol.py", line 234, in _send_request
    self._send(consts.MSG_REQUEST, seq, (handler, self._box(args)))
  File "C:\Python27\lib\site-packages\rpyc\core\protocol.py", line 229, in _send
    self._channel.send(data)
  File "C:\Python27\lib\site-packages\rpyc\core\channel.py", line 69, in send
    self.stream.write(buf)
  File "C:\Python27\lib\site-packages\rpyc\core\stream.py", line 202, in write
    count = self.sock.send(data[:self.MAX_IO_CHUNK])
  File "C:\Python27\lib\site-packages\rpyc\core\stream.py", line 76, in __getattr__
    raise EOFError("stream has been closed")
EOFError: stream has been closed
```

I use rpyc as a bit of a connection service. In other words, the rpyc service readily excepts users and offers a connection interface to a variety of physical connections (serial, usb, database, etc.). The issue that arises above occurs when we request too much data from rpyc at once. 

**For example:**

Suppose rpyc gives us a netref to a database connection. We interface with it using a variety of exposed functionalities. One of those functionalities allows us to query the database directly and get the data back. If for some reason that query pulls back too much data, then the program will crash with the error above. However, the error doesn't show up immediately. It seems to delay until the function finishes. Say we pull back 3000 rows of 5 columns then run some analysis on the data - we won't actually crash until the analysis is through. The following is the actual code snippet where this issue appears:

```
self.postgres_protocol.post_status('')
if self.phase is None:
    self.postgres_protocol.previous_task_id = self.task_obj_id
    self._gather()
    self._analyze()
elif self.phase == '1':
    self._gather()
elif self.phase == '2':
    self._analyze()
self.postgres_protocol.post_status('')
```

Let's say `self.phase == '2'`. Then basically what happens is `self._analyze()` will run the query code, then run the analysis, and finally push the results back to the database. At that point (as soon as `self._analyze` exits), the stream seems to close all on its own. This issue only arises if the query in `self._analyze()` exceeds 2300 records (I assume it's some function of the total data being passed over the stream - not the actual number of records). The stream is dropped then `self.postgres_protocol.post_status('')` draws the error seen above.

Let me know if this is just a basic constraint I'm missing in the documentation or if this appears to be an actual bug in the library. It was a tough one to track down because like I said, the error doesn't actually arise until the function exists. Then the stream drops, and I get an EOFError.

**Comment by coldfix** [comment]
Thanks for your report!

You got an interesting problem here.

> Let me know if this is just a basic constraint I'm missing in the documentation

Not that I'm aware of right now (but I'm a bit new here too).

Is there any way you could create a minimal example?

**Comment by jrg94** [comment]
Unfortunately, I haven't been able to recreate this issue. However, the following snippets should give you a better idea of the code structure for my project.

## Server

```
import rpyc


class MyService(rpyc.Service):
    def on_connect(self):
        pass

    def on_disconnect(self):
        pass

    class exposed_MyObject:
        def exposed_send_data(self):
            return (("This is a demo string", ) * 10, ) * 3000

if __name__ == '__main__':
    from rpyc.utils.server import ThreadedServer
    t = ThreadedServer(MyService, port=18861)
    t.start()
```

## Client

```
import rpyc


class MyClass(object):

    def __init__(self):
        self.c = rpyc.connect("localhost", 18861)
        self.my_object = self.c.root.MyObject()
        self.phase = 1

    def _get_data(self):
        pass

    def run(self):
        self.my_object.send_data()
        if self.phase == 1:
            self._get_data()
        self.my_object.send_data()


class MySubClass(MyClass):
    def _get_data(self):
        print self.my_object.send_data()

if __name__ == '__main__':
    demo = MySubClass()
    demo.run()
```

## Testing

It seems these code snippets can handle as much data as I want. At one point, I tried throwing a 10 x 10000 matrix through it, and I didn't run into any problems. I'm unsure what could be causing the stream to exit prematurely.

If it helps, here is a snippet of the analyze code (with comments removed and variable names changed):

```
def _analyze(self, **kwargs):
    self.postgres_protocol.post_status('Started analysis')
    columns = [
        'some_column_1',
        'some_column_2',
        'some_column_3',
        'some_column_4'
    ]
    data_matrix = self.postgres_protocol.get_data(columns)
    results_dictionary = self.analysis(data_matrix, columns + ['some_column_5'])
    self.postgres_protocol.store_sample(results_dictionary)
    self.postgres_protocol.post_status('Finished analysis')
    self.report_success('analysis_success')
```

The error occurs when the get_data line pulls back at least 2300 records from the database. **However**,  we are still able to interact with the stream until the method exits. For example, you'll see that we're able to run some analysis on the data we retrieve from the database. We're then able to store those results and post a status. Life is good! At that point, the _analyze method exits, the stream closes, and the post status line from the previously mentioned code draws the error.

**Comment by coldfix** [comment]
I'm afraid it's hard to argue about this issue as long as I don't have an example to reproduce.

**Comment by jrg94** [comment]
No problem. I'll try to see if I can isolate what's going on a bit further. The issue is still too bizarre for me to really provide you with some code. Also, the proprietary issue makes it a little tough. :laughing: 

Anyway, I'll close this issue for now. If I find anything further, I'll let you know.
