### ISSUE TITLE
Question - zero deploy & my shinny new service

### ISSUE THREAD

**Issue by liorklip** [tomerfiliba/rpyc#221]
Hi,

I wanted to deploy my service with the zero deploy without hacking your code and changing the SERVER_SCRIPT is there an elegant way to do so?

Thanks!

**Comment by coldfix** [comment]
Did you look at the `server_class` and `extra_setup` arguments for `DeployedServer`? You should be able to customize pretty much anything with those. Otherwise, can you be more specific?

Best, Thomas
