### ISSUE TITLE
runtime error on registry server when disconnecting

### ISSUE THREAD

**Issue by mskoenz** [tomerfiliba/rpyc#224]
First off, thanks for this awesome python library, well done!

This is not really a bug since it does not fail, but there is a runtime error if you run the registry server and disconnect a service (TEST), which should be trivial to fix, I just wanted to bring this to your attention.

> ./bin/rpyc_registry.py -m TCP
DEBUG:REGSRV/TCP/18811:server started on 0.0.0.0:18811
DEBUG:REGSRV/TCP/18811:registering 127.0.0.1:18812 as TEST
DEBUG:REGSRV/TCP/18811:unregistering 127.0.0.1:localhost
DEBUG:REGSRV/TCP/18811:unregistering 127.0.0.1:18812
ERROR:REGSRV/TCP/18811:error executing function
Traceback (most recent call last):
  File "./lib/python3.6/site-packages/rpyc/utils/registry.py", line 138, in _work
    reply = cmdfunc(addrinfo[0], *args)
  File "./lib/python3.6/site-packages/rpyc/utils/registry.py", line 109, in cmd_unregister
    for name in self.services.keys():
RuntimeError: dictionary changed size during iteration

I'm running Python 3.6.1, rpyc==3.4.2 (also tested rpyc==3.4.3) on OSX 10.12.5

Cheers
M

**Comment by coldfix** [comment]
Hi,

thanks for reporting!

Can you quickly paste the client as well to spare me the effort.

**Comment by coldfix** [comment]
Nevermind, I reproduced and fixed with the following client:

```python
import rpyc
from rpyc.utils.registry import TCPRegistryClient
client = TCPRegistryClient('localhost')
client.register(('TEST',), 18812)
client.unregister(18812)
```

Please report back if yours is different and still not working.

Best, Thomas
