### ISSUE TITLE
connection.serve_all blocking other threads from using the connection

### ISSUE THREAD

**Issue by epol** [tomerfiliba/rpyc#225]
Not sure if this is a issue or if I just misusing the library, but I can't find anything in the docs.

When in a multithreaded application i call `rpyc.Connection.serve_all()` from a thread other threads are unable to immediately use the connection.

I think that `serve_all` is blocking the connection and the other threads are able to access it only when there is some timeout.

This code should reproduce the issue

Server:

    #!/usr/bin/env python3
    
    import rpyc
    import rpyc.utils.server
    import threading
    
    class Service(rpyc.Service):
        def on_connect(self):
            print("New connection")
    
        def on_disconnect(self):
            print("Connection closed")
    
        def exposed_get_status(self):
            return "Test string"
    
    server = rpyc.utils.server.ThreadedServer(Service, port = 12345)
    t = threading.Thread(target = server.start)
    t.daemon = True
    t.start()
    t.join()

Client:

    #!/usr/bin/env python3
    
    import rpyc
    import threading
    import datetime
    
    con = rpyc.connect('localhost',12345)
    
    def delayed():
        print("Time is up")
        now = datetime.datetime.now()
        print(con.root.get_status())
        print(str(datetime.datetime.now() - now))
    
    timer = threading.Timer(10,delayed)
    
    print("Starting timer")
    timer.start()
    print("serving all")
    con.serve_all()

Sample output (from the client):

    $ python3 testrpyc.py 
    Starting timer
    serving all
    Time is up
    Test string
    0:01:30.064087

I'm using RPyC 3.4.3 on Python 3.5.4rc1 (debian sid) installed with pip.

**Comment by coldfix** [comment]
This is true. As a general rule of thumb, you should perform IO only from a single thread on *any* single resource.

**Comment by epol** [comment]
Ok, thank you for your reply. I'll keep it in mind.

I think that in a old version (maybe before a00be891a, I'm not sure since I lost the old installation) it worked to use the same connection across multiple threads, that's why I asked before rewriting my code.

**Comment by epol** [comment]
Would it be safe to open a new connection for every single thread? Or should I keep only one connection on one thread?

**Comment by coldfix** [comment]
> Would it be safe to open a new connection for every single thread?

Should be.

> Or should I keep only one connection on one thread?

Depends on what you're trying to do. In general, multithreading is not an easy problem and there may be many answers to that question.

**Comment by epol** [comment]
Thank you again for your time and for your work on this great library.
