### ISSUE TITLE
Does `rpyc_classic.py` exist any more?

### ISSUE THREAD

**Issue by ssteinerx** [tomerfiliba/rpyc#227]
I've installed with pip and `rpyc_classic.py` is nowhere to be found, nor is it in the file tree of a git checkout.

There was a change to the docs vis-à-vis name and location in the tutorial:
```
Update tutorial start for new rpyc_classic.py location
```
 https://github.com/tomerfiliba/rpyc/commit/98a9a89889705c888a9dbe0435ce3c105b7bb2a1

But the file doesn't seem to be around anywhere.

**Comment by coldfix** [comment]
In a git checkout, it's right there in `bin/rpyc_classic.py` as the documentation change that you linked says.

If you install with pip, it should be installed into your PATH, justr try running `rpyc_classic.py`.

It's also included in the source distribution. I checked.

**Comment by ssteinerx** [comment]
Humblest apology -- my mistake.

Note to self: when looking for things that only exist in newer versions of a project, update your fork before looking for them.

I had an old fork around and that's what `git pull` etc. were referencing, not the current version.

**Comment by bor8** [comment]
I found mine in /usr/local/bin/.
