### ISSUE TITLE
rpyc_classic.py help messages no daemon method

### ISSUE THREAD

**Issue by hgz6536** [tomerfiliba/rpyc#230]
can carpyc_classic.py running in the daemon ?

**Comment by coldfix** [comment]
Do you mean running the classic server in background mode? There is no such option yet, but it should not be too hard to accomplish using libraries like [python-daemon](https://pagure.io/python-daemon/) or [daemonize](https://github.com/thesharp/daemonize). I'm open to accept pull-requests in this matter.

**Comment by coldfix** [comment]
Let me correct my previous answer, sorry: `bin/rpycd.py` does basically that using `python-daemon`.

Please reopen, if this was not your question.
