### ISSUE TITLE
Errors working with SlaveService<->Other Service

### ISSUE THREAD

**Issue by aspir** [tomerfiliba/rpyc#232]
I try to create a simple connection between SlaveService and some regular Service(non SlaveService).

**Server.py**
```
import rpyc
from rpyc.utils.server import ThreadedServer

a = ThreadedServer(rpyc.SlaveService, port=4567)
a.start()
```

**client.py**
```
import rpyc
import time

conn = rpyc.connect("localhost", port=4567, service=rpyc.VoidService)
print(conn.modules.sys.argv) # throws here exception
while True:
    time.sleep(1)
```

and I get errors like "AttributeError: cannot access 'modules'" when I try to work with the connection_object in client.py.

When working with SlaveService, the other Service has to be SlaveService? Why its only happens when working with SlaveService?

**Comment by coldfix** [comment]
Hi,

good question. IMO, there should be no need. First, there is a small issue with your server: `on_connect` should call `super().on_connect()` to make sure the `SlaveService.on_connect` is executed.

Furthermore, unless I'm missing something about why classic mode needs to operate bidirectionally, I think there has been a mixup of server/client logic while writing the classic module:

`SlaveService.on_connect` is used to set `.modules` and other attributes of the `Connection`. This has two consequences:

- `conn.modules` attribute is only set on the client connection if instanciated with `SlaveService`. This part is really easy to work around in your code by manually instanciating `modules = ModuleNamespace(conn.root.getmodule)`.

- Second consequence is that the server tries to get hold of a `ModuleNamespace` (and other things) on the client - but this is only available if the client exposes a `SlaveService`.

Both issues can be resolved by moving most of the assignments within the `SlaveService.on_connect` (`rpyc/core/service.py:129`) to a more sensible location not tied to `SlaveService` and only executed by the classic client.

I'm open for pull requests.

**Comment by aspir** [comment]
Hi coldfix thank you for the fast response.
if I will add to the client:
`modules = ModuleNamespace(conn.root.getmodule)`
Won't it give the server the ability to work with every module in the client context? and if not, why?

nevertheless, can we discuss this issue privately?

**Comment by coldfix** [comment]
> 
if I will add to the client:
modules = ModuleNamespace(conn.root.getmodule)
Won't it give the server the ability to work with every module in the client context? and if not, why?

No, this just creates an object that represents all remote modules, i.e gives the local side of the connection the ability to access all remote modules.

> nevertheless, can we discuss this issue privately?

If you see the need just send me an email or propose sth else.
