### ISSUE TITLE
connect be close, it can reconnect and the running environment still exist?

### ISSUE THREAD

**Issue by getixin** [tomerfiliba/rpyc#233]
conn = rpyc.classic.connect('10.66.80.232')
rp = conn.modules.suprocess.Popen('ping 127.0.0.1 -n 100')

and then off network the conn be closed
the command is running? or the conn can reconnect?

**Comment by coldfix** [comment]
There is currently no reconnection mechanism in rpyc. You can create a new connection manually if you notice that the connection is down, but it will create new Service objects.
