### ISSUE TITLE
very slow remote performance

### ISSUE THREAD

**Issue by hatRiot** [tomerfiliba/rpyc#234]
Apologize if this has been noted elsewhere, I was unable to find a reference.  Essentially, when tossing objects around RPyC systems over VPNs or across Internet hosts, the performance is quite awful.

As example, here is my server:

```
import rpyc

class TestObject(object):
    def __init__(self):
        self.intvalue = 123
        self.stringvalue = "test string!"
        self.otherobj = None

class TestService(rpyc.Service):
    def on_connect(self):
        print('Got connection')

    def exposed_fetch_stuff(self):
        values = []
        for i in range(20):
            x = TestObject()
            x.intvalue = i
            values.append(x)

        return values

if __name__ == "__main__":
    from rpyc.utils.server import ThreadedServer
    t = ThreadedServer(TestService, port=18861,
                    protocol_config = {'allow_all_attrs':True,
                    'allow_pickle':True,
                    'allow_setattr':True,
                    'allow_public_attrs':True})
    t.start()
```

And the client:
```
import rpyc
import time

try:
    connection = rpyc.connect("localhost", 18861,
                    config={'allow_all_attrs':True,
                            'allow_pickle':True})
    bgt = rpyc.BgServingThread(connection)

    start = time.time()
    data = connection.root.fetch_stuff()

    [str(x.intvalue) for x in data]
    ['%s-'%x.stringvalue for x in data]

    end = time.time()
    print(end - start)

    connection.root.put_stuff(data)
except Exception, e:
    print e
```

The access time of this is upwards of 6.72!  However, if I employ deep copying on the client:
```
data = copy.deepcopy(data)
```

And add the TestObject class to the client, the performance improves dramatically to just ~0.59.  I understand this is likely due to the constant synchronization of objects occurring, but are there any other alternatives to deepcopying?  Our issue there is we have quite a few custom classes and would like a reliable way to proxy/teleport them without having to add all class definitions to the client.

**Comment by coldfix** [comment]
Hi,

on localhost this kind of performance is completely abnormal. The test script you posted reports a runtime of 0.015s on my system (and then fails because `put_stuff` is not defined on the server). Are you using cpython?

That being said, if you do use rpyc over connections with high latency, it is expected to perform badly. There is not a lot you can do about that except for plan ahead and transfer objects to the local party like you did.

**Comment by hatRiot** [comment]
Thanks @coldfix 

The localhost binding used is just a dummy address, as I did not want to reveal my VPS IP address.  If you run the server in AWS/Azure/some other VPS and connect via the client, you should see much higher response times.

**Comment by coldfix** [comment]
Sorry, accidentally closed wrong issue :P

**Comment by mmeade** [comment]
I'm seeing the same thing, but it's happening regardless of network setup.

I calculate the bandwidth to the remote machine at connect time, simply calling an empty method with fixed sized data and calculating the upload time. I've found wildly varying bandwidths in a single run by changing the length of the string passed to it.

Here are some of the speeds I've seen:
1B - 26.5bps
512B - 39Kbps - based on a linear scale this should be ~12Kbps
1 KB - 80Kbps - based on a linear scale this should be ~25Kbps
512KB - 37.4Mbps - based on a linear scale this should be ~1Mbps
1MB - 80Mbps - based on a linear scale this should be ~25Mbps
512MB - 378Mbps - based on a linear scale this should be ~1Gbps

So the actual bandwidth is worse than the linear calculation when data size is between 512KB and 1MB.

I ran it through a custom port forwarding server to find out what the bandwidth is outside of RPYC. I measured the time for the read as well as the write. I found the following:

client->server - 1024B read size - >1024B data length - 56Mbps
client->server - 1024B read size - 898B data length -  47Mbps
client->server - 1024B read size - 31B data length - 139Kbps
client->server - 1024B read size - 14B data length - 185Kbps
server->client - 1024B read size - 12B data length - 554Kbps

I found that the lower limit tends to be 300ms to send a single character. Obviously larger data sets will be more efficient, but it seems that most of the traffic being passed are probably in the KB range. If this is the case the standard operation of RPYC seems to be artificially throttled. Is there anything in the networking stack that throttles sends? Is there a buffer that tries to combine requests to lower the overhead with a timeout to signal a send?

**Comment by coldfix** [comment]
Hi, I don't fully follow what you did exactly.

If you measured the total bandwith of data transferred, while issueing a number of (synchronous) requests, it's pretty obvious that performance gets pretty bad for small payloads: first, there is an overhead on each request, second, synchronous requests wait for the reply before the next one can start, so your bandwidth will be limited by your ping..

If this is not what you did, please elaborate.
