### ISSUE TITLE
__new__ is in safe_attrs

### ISSUE THREAD

**Issue by seveirein** [tomerfiliba/rpyc#242]
If ``__init__`` is not deemed to be a ``safe_attr``, there is no reason to have ``__new__`` as a ``safe_attr``.

https://github.com/tomerfiliba/rpyc/blob/master/rpyc/core/protocol.py#L35

This seems like asking for trouble.

**Comment by seveirein** [comment]
Hmm, if a netref proxies a class it may have ``__new__`` called on it as part of having a new object being instantiated. This would also typically have an ``__init__`` call.  I believe ``__new__`` is listed as a ``safe_attr`` so when ``__init__`` is exposed, it just works, instead of having to expose both.

This seems dangerous as some objects bypass `__init__` altogether (hopefully not ones proxied on) and just use `__new__`.  This allows some dynamism in terms of object type constructed. 

I propose that `__new__` should only be a safe_attr conditionally when ``__init__`` is exposed somehow. Otherwise it should be exposed only if explicitly exposed (IE via ``exposed___new__``, ``allow_unsafe_attrs``, or ``_rpyc_getattr``).

**Comment by coldfix** [comment]
Hi,

> If `__init__` is not deemed to be a `safe_attr`, there is no reason to have `__new__` as a `safe_attr`.

As you noted, you can construct instances with `__new__` but not with `__init__`. The latter is typically only useful for subclassing and that's not supported anyway for now.

On the other hand, probably one would rarely need to call `__new__` explicitly either. Typically, just calling the class netref would be enough.

> This seems like asking for trouble.

I'm not sure how `__new__` is more trouble than the other *"safe"* attributes. Other methods, such as `__add__` for example, allow for object construction too. If you want to be safe, you should disable `allow_safe_attrs` or specify a selected subset manually. (One might argue, what's the point then of having this default, why not just have either full slave mode or all user-controlled access? I don't know, that would probably make more sense to me..)

> I propose that `__new__` should only be a safe_attr conditionally when `__init__` is exposed somehow. Otherwise it should be exposed only if explicitly exposed (IE via `exposed___new__`, `allow_unsafe_attrs`, or `_rpyc_getattr`).

I don't see any reason to introduce even more complexity here. It doesn't make anything safer, just harder to explain and understand.

> The alternative is to just remove it and require people to expose both `__new__` and `__init__`. It would be more likely to break current usage, but there'd wouldn't be any dynamic exposure decisions going on behind the curtains.

That's an option, but I'm not sure of the benefits. If you convince me, I don't mind breaking backward compatibility here, as it's easy to fix on the user side and probably not in common use.

Best, Thomas

**Comment by coldfix** [comment]
Closing this for now. Feel free to reopen, if you can substanciate why `__new__` is a problem. Best, Thomas
