### ISSUE TITLE
Passing objects across connections

### ISSUE THREAD

**Issue by skeledrew** [tomerfiliba/rpyc#249]
Hi,

I'm trying to use rpyc as a memoize framework to hopefully speed up data access (keep in memory instead of reading from disk each time). As such I have implemented the foll. service:
``` python
class MemoryService(rpyc.Service):

    def on_connect(self):
        if not '_blob' in globals(): self._blob = {}

    def on_disconnect(self):
        pass

    def exposed_blob(self, caller_id, key, data=None):
        if not caller_id or (not caller_id in self._blob and not data): return ValueError('Invalid caller_id')
        if not data: return self._blob[caller_id].get(key, ValueError('Specified key does not exist'))
        if not caller_id in self._blob: self._blob[caller_id] = {}
        self._blob[caller_id][key] = data
        return True
```
but found that I cannot access the blob across connections, so I tried implementing a new server instead of using ThreadedServer, etc, but it still doesn't help (I imported `server` into `rpyc` as for some reason I can't directly access `rpyc.utils.server`):
``` python
class SingletonServer(rpyc.server.Server):
    '''
    A server that does everything in a single thread.
    '''

    def _accept_method(self, sock):
        try:
            self._authenticate_and_serve_client(sock)

        except Exception as e:
            print('Something broke: ' + repr(e))
```

- expected result versus actual result
-- I can access the objects I put in the blob fine until I create a new connection, then I get the error that the object isn't present.
- steps to reproduce
-- Add the above classes to a file along with:
``` python
if __name__ == '__main__':
    port = 9998 if len(sys.argv) < 2 else int(sys.argv[1])
    #from rpyc.utils.server import ThreadedServer

    t = SingletonServer(MemoryService, 'localhost', port=port)
    print('Running MemoryService on port %s. Use Ctrl+C to quit.' % (port))
    t.start()
    print('Killing MemoryService.')
```
-- Start the server
-- Enter into an interpreter:
```>>> import rpyc
>>> c = rpyc.connect('localhost', 9998)
>>> c.root
<__main__.MemoryService object at 0x7f85c613d708>
>>> c.root.blob
<bound method MemoryService.exposed_blob of <__main__.MemoryService object at 0x7f85c613d708>>
>>> c.root.blob('test', 'k')
ValueError('Invalid caller_id',)
>>> c.root.blob('test', 'k', 12345)
True
>>> c.root.blob('test', 'k')
12345
>>> del c
>>> c = rpyc.connect('localhost', 9998)
>>> c.root.blob('test', 'k')
ValueError('Invalid caller_id',)
```

Any ideas where I'm going wrong? Thanks.

##### Environment

- rpyc version 3.4.4
- python version 3.4.5
- operating system "Linux HSDNLP 2.6.32-696.6.3.el6.x86_64 #1 SMP Wed Jul 12 14:17:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux" (output from uname -a)

**Comment by coldfix** [comment]
Is your issue the same as in #198, i.e. you expect the same service instance to be shared for multiple services?

If so, see my last comment in that thread on how to do it starting next release.

With the current release, you could do it by passing to the server a service instance and defining a `__call__` method (see my second code snippet in [#244](https://github.com/tomerfiliba/rpyc/issues/244#issuecomment-351262006).

Best, Thomas

**Comment by skeledrew** [comment]
Actually my use case is a bit different. I do NLP research, which involves creating very huge YAML files with the results from my scripts ( a few GB), which I think have to read again to extract particular results. The problem is that due to the size of the file it can take from a few minutes to a couple hours just to read and parse, so it can be a real pain esp since I may modify the script that reads the results, and an error means I have to fix and read the file again from scratch. 

So I want to use rpyc to store the file content in a server the first time it's read, then access it from that server each time the client script is subsequently run. This means on connecting the client it should access the same server and service instance without having a particular connection or service object to pass. This is the client that I'm using to interface with the server https://github.com/skeledrew/medical-nlp-research/blob/master/common.py#L392 and this is where I'm currently using it https://github.com/skeledrew/medical-nlp-research/blob/master/export_results.py#L35

Thanks.

**Comment by coldfix** [comment]
Hi,

I don't see any difference. If I understand correctly, there is one specific large object that you want to serve on all incoming connections. This can be done by either:

- passing mentioned object to all service instances, you can do this with e.g. globals, abusing the `config` dict, or other tricks as mentioned in #244 
- reusing the same service object for all clients, in the lines of #198, this will be much simplified starting with the next version

In case you want to have multiple client-specific large data object that will stay alive when a client disconnects and later reconnects: there is no logic in rpyc that assumes to know how to identify a particular client. You would have to create your own code that manages sessions, identifies clients, and looks up the correct data.

Please reopen if I misunderstood.

Best, Thomas
