### ISSUE TITLE
Async is a keyword in Python 3.7

### ISSUE THREAD

**Issue by pyscripter** [tomerfiliba/rpyc#253]
Since async was made a keyword in Python 3.7 rpyc will fail to compile.  The async module needs to be renamed.

**Comment by coldfix** [comment]
Hi, I don't mind renaming it to async_ or similar. However, the python 3.7 builds on travis are still passing, are you sure async is a reserved word in all contexts?

(I thought it was only recognized in certain syntactical constructs, e.g. before `def` or `for` etc)

**Comment by pyscripter** [comment]
That was fast! :)
Thanks

**Comment by coldfix** [comment]
Thanks!

> *** Python 3.7.0a4 (v3.7.0a4:07c9d85, Jan  9 2018, 06:16:56) [MSC v.1900 32 bit (Intel)] on win32. ***


That explains it. Travis 3.7 tests seem to run on an earlier build (3.7.0a0).

I wonder why this change is not listed in the [What's New In Python 3.7](https://docs.python.org/3.7/whatsnew/3.7.html), had to look up the respective PEP to go sure https://www.python.org/dev/peps/pep-0492/#deprecation-plans..
