### ISSUE TITLE
Cannot Install 3.4.4

### ISSUE THREAD

**Issue by micksulley** [tomerfiliba/rpyc#261]
Hi,

I've used previous versions but I am just trying to install RPyC on a new machine, figured I would use the latest version and I can't work out how to do it.

Trying to install on Ubuntu server 17.10

I downloaded rpyc-3.4.4-py2-none-any.whl into a new directory and used pip to install.  Here is what I got.

mick@zen:~/.rpyc$ pip install rpyc-3.4.4-py2-none-any.whl
Processing ./rpyc-3.4.4-py2-none-any.whl
Collecting plumbum (from rpyc==3.4.4)
  Using cached plumbum-1.6.6-py2.py3-none-any.whl
Installing collected packages: plumbum, rpyc
Successfully installed plumbum-1.6.6 rpyc-3.4.4
mick@zen:~/.rpyc$

But I cannot run it.  There is no 'rpyc_classic.py' anywhere.

Have I missed something? Can anyone help me please?

Thanks

Mick

**Comment by coldfix** [comment]
Hi, the title of your issue is a little misleading since you later say that you have successfully installed rpyc. Anyway, once the installation is done `rpyc_classic.py` should normally be available in your PATH. If your terminal doesn't know about it, I'd say it's most likely that it didn't rehash PATH contents yet. Did you try closing and reopening a new terminal window?

**Comment by micksulley** [comment]
I have successfully installed previous versions on other machines.  This is a fresh install of Ubuntu Server 17.10 and I am trying to install RPyC 3.4.4
As I said after trying to install it with pip it seems to complete OK but rpyc_classic.py does not exist anywhere on the machine, so it obviously hasn't installed it.  How should I do it?

**Comment by coldfix** [comment]
Please show the output of `pip uninstall rpyc`.

**Comment by micksulley** [comment]
`mick@zen:~$ pip uninstall rpyc
Uninstalling rpyc-3.4.4:
  /home/mick/.local/bin/rpyc_classic.py
  /home/mick/.local/bin/rpyc_classic.pyc
  /home/mick/.local/bin/rpyc_registry.py
  /home/mick/.local/bin/rpyc_registry.pyc
  /home/mick/.local/lib/python2.7/site-packages/rpyc-3.4.4.dist-info/DESCRIPTION.rst
  /home/mick/.local/lib/python2.7/site-packages/rpyc-3.4.4.dist-info/INSTALLER
  /home/mick/.local/lib/python2.7/site-packages/rpyc-3.4.4.dist-info/METADATA
  /home/mick/.local/lib/python2.7/site-packages/rpyc-3.4.4.dist-info/RECORD
  /home/mick/.local/lib/python2.7/site-packages/rpyc-3.4.4.dist-info/WHEEL
  /home/mick/.local/lib/python2.7/site-packages/rpyc-3.4.4.dist-info/metadata.json
  /home/mick/.local/lib/python2.7/site-packages/rpyc-3.4.4.dist-info/top_level.txt
  /home/mick/.local/lib/python2.7/site-packages/rpyc/__init__.py
  /home/mick/.local/lib/python2.7/site-packages/rpyc/__init__.pyc
  /home/mick/.local/lib/python2.7/site-packages/rpyc/core/__init__.py
  /home/mick/.local/lib/python2.7/site-packages/rpyc/core/__init__.pyc
  /home/mick/.local/lib/python2.7/site-packages/rpyc/core/async.py
  /home/mick/.local/lib/python2.7/site-packages/rpyc/core/async.pyc
  /home/mick/.local/lib/python2.7/site-packages/rpyc/core/brine.py
  /home/mick/.local/lib/python2.7/site-packages/rpyc/core/brine.pyc
  /home/mick/.local/lib/python2.7/site-packages/rpyc/core/channel.py
  /home/mick/.local/lib/python2.7/site-packages/rpyc/core/channel.pyc
  /home/mick/.local/lib/python2.7/site-packages/rpyc/core/consts.py
  /home/mick/.local/lib/python2.7/site-packages/rpyc/core/consts.pyc
  /home/mick/.local/lib/python2.7/site-packages/rpyc/core/netref.py
  /home/mick/.local/lib/python2.7/site-packages/rpyc/core/netref.pyc
  /home/mick/.local/lib/python2.7/site-packages/rpyc/core/protocol.py
  /home/mick/.local/lib/python2.7/site-packages/rpyc/core/protocol.pyc
  /home/mick/.local/lib/python2.7/site-packages/rpyc/core/reactor.py
  /home/mick/.local/lib/python2.7/site-packages/rpyc/core/reactor.pyc
  /home/mick/.local/lib/python2.7/site-packages/rpyc/core/service.py
  /home/mick/.local/lib/python2.7/site-packages/rpyc/core/service.pyc
  /home/mick/.local/lib/python2.7/site-packages/rpyc/core/stream.py
  /home/mick/.local/lib/python2.7/site-packages/rpyc/core/stream.pyc
  /home/mick/.local/lib/python2.7/site-packages/rpyc/core/vinegar.py
  /home/mick/.local/lib/python2.7/site-packages/rpyc/core/vinegar.pyc
  /home/mick/.local/lib/python2.7/site-packages/rpyc/experimental/__init__.py
  /home/mick/.local/lib/python2.7/site-packages/rpyc/experimental/__init__.pyc
  /home/mick/.local/lib/python2.7/site-packages/rpyc/experimental/retunnel.py
  /home/mick/.local/lib/python2.7/site-packages/rpyc/experimental/retunnel.pyc
  /home/mick/.local/lib/python2.7/site-packages/rpyc/experimental/splitbrain.py
  /home/mick/.local/lib/python2.7/site-packages/rpyc/experimental/splitbrain.pyc
  /home/mick/.local/lib/python2.7/site-packages/rpyc/lib/__init__.py
  /home/mick/.local/lib/python2.7/site-packages/rpyc/lib/__init__.pyc
  /home/mick/.local/lib/python2.7/site-packages/rpyc/lib/colls.py
  /home/mick/.local/lib/python2.7/site-packages/rpyc/lib/colls.pyc
  /home/mick/.local/lib/python2.7/site-packages/rpyc/lib/compat.py
  /home/mick/.local/lib/python2.7/site-packages/rpyc/lib/compat.pyc
  /home/mick/.local/lib/python2.7/site-packages/rpyc/utils/__init__.py
  /home/mick/.local/lib/python2.7/site-packages/rpyc/utils/__init__.pyc
  /home/mick/.local/lib/python2.7/site-packages/rpyc/utils/authenticators.py
  /home/mick/.local/lib/python2.7/site-packages/rpyc/utils/authenticators.pyc
  /home/mick/.local/lib/python2.7/site-packages/rpyc/utils/classic.py
  /home/mick/.local/lib/python2.7/site-packages/rpyc/utils/classic.pyc
  /home/mick/.local/lib/python2.7/site-packages/rpyc/utils/factory.py
  /home/mick/.local/lib/python2.7/site-packages/rpyc/utils/factory.pyc
  /home/mick/.local/lib/python2.7/site-packages/rpyc/utils/helpers.py
  /home/mick/.local/lib/python2.7/site-packages/rpyc/utils/helpers.pyc
  /home/mick/.local/lib/python2.7/site-packages/rpyc/utils/registry.py
  /home/mick/.local/lib/python2.7/site-packages/rpyc/utils/registry.pyc
  /home/mick/.local/lib/python2.7/site-packages/rpyc/utils/server.py
  /home/mick/.local/lib/python2.7/site-packages/rpyc/utils/server.pyc
  /home/mick/.local/lib/python2.7/site-packages/rpyc/utils/teleportation.py
  /home/mick/.local/lib/python2.7/site-packages/rpyc/utils/teleportation.pyc
  /home/mick/.local/lib/python2.7/site-packages/rpyc/utils/zerodeploy.py
  /home/mick/.local/lib/python2.7/site-packages/rpyc/utils/zerodeploy.pyc
  /home/mick/.local/lib/python2.7/site-packages/rpyc/version.py
  /home/mick/.local/lib/python2.7/site-packages/rpyc/version.pyc
Proceed (y/n)? 
`

**Comment by coldfix** [comment]
The first few lines show that `rpyc_classic.py` was in fact installed:

```
Uninstalling rpyc-3.4.4:
  /home/mick/.local/bin/rpyc_classic.py
```

In order to use scripts installed by `pip install --user` you have to add `$HOME/.local/bin` to PATH. Add the following line to `~/.bashrc` or `~/.zshrc` (depending on what shell you're using):

```bash
PATH="$PATH:$HOME/.local/bin"
```
