### ISSUE TITLE
Update SSH Documentation

### ISSUE THREAD

**Issue by Denton-L** [tomerfiliba/rpyc#274]
In [this documentation](https://github.com/tomerfiliba/rpyc/blob/master/docs/docs/secure-connection.rst#ssh-tunneling), SSH is discussed. However, this is outdated information since `rypc.utils.ssh` was removed a long time ago.

The documentation should be updated to reflect the new changes.

Thanks!

**Comment by coldfix** [comment]
Good catch. It appears the `rpyc.utils.ssh` was removed in favor of letting `plumbum` handle SSH tunneling. I have updated the documentation, please let me know if you encounter further problems.

**Comment by Denton-L** [comment]
Wow, that was a quick fix! Thanks so much!
