### ISSUE TITLE
Run lambda functions on remote machine

### ISSUE THREAD

**Issue by kfir-drivenets** [tomerfiliba/rpyc#285]
Currently if you pass a callable argument via an RPyC exposed method that callback will invoked on the client side. This is by design and explained in the docs (http://rpyc.readthedocs.io/en/latest/tutorial/tut4.html).
In some scenarios one might want to run a specific callable on the remote end.
For example lets assume that I use RPyC service to query a large data structure. One of the parameters that I pass to the exposed method is a lambda function that performs custom filtering on each entry in the data structure. This flow will work a lot faster if the lambda can be executed on the remote machine.

As far as I saw in the docs there isn't a way to do this with the current API.

Example service:
```python
import typing
import rpyc

class SuperService(rpyc.Service):
    def __init__(self, *args, **kwrags):
        self._my_huge_list = [.....]

    def exposed_query(self, entry_filter: typing.Callable):
        return [ element for element in filter(entry_filter, self._my_huge_list) ]
```

Example client:
```python
import rpyc
client = rpyc.connect(...)
client.root.query(lambda x: x > 2)

````

Thanks in advance,
Kfir.

**Comment by kfir-drivenets** [comment]
I ended up with a hack that solved my specific needs.
I use `dill` to pack my lambda function, send it to the other side (as a parameter), unpack it and execute it there.

```python
import dill
my_filter = dill.dumps(lambda x: x > 2)
client.root.query(entry_filter=my_filter)
```

**Comment by coldfix** [comment]
Did you try `rpyc.utils.classic.teleport_function` (currently only works in classic mode)?

**Comment by kfir-drivenets** [comment]
@coldfix nope, honestly after figuring out that I can do what I wanted with dill I found a solution that is good enough for my use case.
It will be nice to have this feature inside the services some how..

**Comment by coldfix** [comment]
I guess it would make a reasonable addition to classic connections (considering they already have similar methods `exec`, `eval` etc). I will see if I have time to include it anytime soon. Thanks for the feedback.
