### ISSUE TITLE
rpyc connection drops observed when server and client in NAT based private network and 7%packet losss 

### ISSUE THREAD

**Issue by madhukeshava** [tomerfiliba/rpyc#286]
Describe the issue briefly here, including:
we are noticing frequent connection drop from client to server when we used private network using NAT based approach.... 
can you please suggest what is best way to handle these kind of connection failures...
 try:

            hadnle =rpyc.classic.connect
            self.p = hadnle .modules.subprocess.Popen(cmdstr,
                        cwd=self.cwd,
                        shell=True,
                        stdout=subprocess.PIPE,
                        stderr=subprocess.STDOUT)   #TODO PIPE?
        except EOFError:
            LOGGER.critical('%s connection failure', self.connection['name'])
            self.p = None
- expected result versus actual result
   

- involved/problematic methods, e.g. `__call__`
- steps to reproduce
- for bugs, please attach a

```
stack trace / error log
```

##### Environment

- rpyc version
- python version
- operating system

##### Minimal example

Server:

```python
import rpyc
from rpyc.utils.server import OneShotServer
rpyc.lib.setup_logger()

class ListService(rpyc.Service):
    def exposed_concat(self, lst):
        return lst + ['world']

server = OneShotServer(ListService, port=12345)
server.start()
```

Client:

```python
import rpyc
c = rpyc.connect("localhost", 12345)
print(c.root.concat(['hello']))
```

**Comment by coldfix** [comment]
Sorry, the information given is insufficient and you put almost no effort into making the report leaving it to me to guess what is the problem.
