### ISSUE TITLE
ThreadPoolServer auto close

### ISSUE THREAD

**Issue by melvinkcx** [tomerfiliba/rpyc#287]
ThreadPoolServer auto close when started. I spawned an instance of ThreadPoolServer, when trying to start(), it immediately closes after started. If I switch it too ThreadedServer, it works properly. 

This is my code to spawn a ThreadPoolServer:
```
    # Spawn a log server
    log_server = ThreadedServer(
        classpartial(LoggingService, settings),
        port=service_port,
        protocol_config={
            'allow_public_attrs': True,
        },
    )

    log_server.start()
```
The log message that I got:
```
INFO:KT_LOGGING_WRITE/10002:server has terminated
INFO:KT_LOGGING_WRITE/10002:listener closed
```

When trying to spawn a ThreadedServer:
```
    # Spawn a log server
    log_server = ThreadedServer(
        classpartial(LoggingService, settings),
        port=service_port,
        protocol_config={
            'allow_public_attrs': True,
        },
    )

    log_server.start()
```

It starts and works properly:
```
INFO:KT_LOGGING_WRITE/10002:server started on [0.0.0.0]:10002

```

I am using Python 3.6, RpyC 4.0.1, Manjaro Linux.

**Comment by melvinkcx** [comment]
I'm not sure if I'm doing this right, but somehow I could make the ThreadPoolServer to work, but removing this link in ThreadPoolServer.__init__()
```
 def __init__(self, *args, **kwargs):
        ...
        # declare the pool as already active
        self.active = True # Comment this line
        ...
```

**Comment by AlinMH** [comment]
#283 Check this issue, it's the same thing, I guess.

**Comment by coldfix** [comment]
Hi, thanks, this appears to be the same issue indeed. Closing in Favor of #283.
