### ISSUE TITLE
reduce round-trip network traffic by adding _io to builtins

### ISSUE THREAD

**Issue by delandtj** [tomerfiliba/rpyc#295]
adding these saves two round-trips and over 500 bytes of traffic.  actually only _io.TextIOWrapper is the culprit: however adding all the others makes sense.  they're in the built-in module  "_io" which is a standard c-based python module in both 2.7 and 3.  may make sense to put this unconditionally (not with the ispy3k test?)

 ```

diff --git a/rpyc/core/netref.py b/rpyc/core/netref.py
index 6cf6ff1..c24211f 100644
--- a/rpyc/core/netref.py
+++ b/rpyc/core/netref.py
@@ -7,6 +7,7 @@ import inspect
 import types
 from rpyc.lib.compat import pickle, is_py3k, maxint, with_metaclass
 from rpyc.core import consts
+import _io
 
 
 # If these can be accessed, numpy will try to load the array from local memory,
@@ -50,6 +51,17 @@ if is_py3k:
         bytes, bytearray, type(iter(range(10))), memoryview,
     ])
     xrange = range
+
+    # look for builtin io.String (actually _io.String), TextIOWrapper
+    # and others.  saves a lot of network traffic when using IPython.embed
+    for ioname in dir(_io):
+        if ioname.startswith("__"):
+            continue
+        ioattr = getattr(_io, ioname)
+        if not inspect.isclass(ioattr):
+            continue
+        _builtin_types.append(ioattr)
+        print ("adding ioname", ioname)
 else:
     _builtin_types.extend([
         basestring, unicode, long, xrange, type(iter(xrange(10))), file,
```

**Comment by coldfix** [comment]
> adding these saves two round-trips and over 500 bytes of traffic.

but increases traffic for applications where it's not used (not that a bit of traffic matters too much..).

>  actually only _io.TextIOWrapper is the culprit:

is there any particular reasons why you add all classes from `_io` then? I would prefer an explicit list, as is done for the other types.

>  they're in the built-in module "_io" which is a standard c-based python module in both 2.7 and 3

Though it's less basic than the other types listed here and not used as commonly.

I'm thinking whether it's best to provide an API that let's the user add types which he anticipates to be queried later. It would be more generic and allow even more savings by adding non-standard types. It can already be done:

```python
from rpyc.core.netref import _builtin_types
_builtin_types.extend([
   _io,TextIOWrapper, ...,
])
```

but that's of course not a good API..

**Comment by delandtj** [comment]
yeah allowing users to add types they know will be on both sides is a great idea.  you should have seen how much network traffic there was for the class i was investigating [and knew was on both sides].  it *may* even be worthwhile considering doing some sort of automated sha256 (or crc32) checksumming (like rsync, if you're familiar with that? it's a 1% overhead for files that are identical on both sides) which would do a checksum of the class, send *that*, and if it's the same then obviously there's no need to send all the data about the class.

**Comment by delandtj** [comment]
> is there any particular reasons why you add all classes from _io then? 

it was just the quickest way i could think of to get the job done, not ever having used rpyc before.

**Comment by delandtj** [comment]
> Though it's less basic than the other types listed here and not used as commonly.

anyone using IPython interactive shell, it's used by that.  and i believe IPython shell is one of the main recommended uses for rpyc (as an alternative to it, i think i read somewhere?)

**Comment by comrumino** [comment]
Tracking at #326
