### ISSUE TITLE
Statically typed brine-ish serializer (improve brine)

### ISSUE THREAD

**Issue by traverseda** [tomerfiliba/rpyc#301]
https://gist.github.com/61dedd1a5f1ac3a8f9a825a0ecf300fc

I wrote a serializer that does the same thing as brine, but has type-annotations and is ~1/2 the size. I also think it's a fair bit more readable (aside from the code for encoding ints) and it is much easier to extend.

It's also not backwards compatible. I figured I'd mention that it exists, and that rpyc is free to use it. It's a pretty significant refactor, but it might be a good choice for the next major release.

**Comment by coldfix** [comment]
Cool! Did you do any performance benchmarks so far? This might be worth adding once we drop py2 support.

**Comment by traverseda** [comment]
I did some quick naive testing.

from a cold-ish start I got

    0.05user 0.00system 0:00.05elapsed 98%CPU (0avgtext+0avgdata 9872maxresident)k #My serializer
   0.08user 0.01system 0:00.09elapsed 98%CPU (0avgtext+0avgdata 16992maxresident)k #brine

for one (encode-decode) cycle.

For 5000 cycles I got

    0.31user 0.00system 0:00.32elapsed 99%CPU (0avgtext+0avgdata 10036maxresident)k
 #my serializer
    0.14user 0.00system 0:00.15elapsed 98%CPU (0avgtext+0avgdata 17104maxresident)k #brine

So my implementation is a bit slower, maybe because we use a dictionary to store type IDs instead of defining them inline. It could also be because we use variable-length integer encoding to specify how long an object is. The upside is that large objects should use less IO and memory.

I don't think it's because of the dictionary lookups, as hash-tables tend to be as fast as native lookups, since python's namespaces are built on dictionaries.

**Comment by comrumino** [comment]
Tracking at #326
