### ISSUE TITLE
Execute yield command remotely

### ISSUE THREAD

**Issue by andresdemski** [tomerfiliba/rpyc#302]
Hello,
I'm trying to use RPyC in a proyect based in coroutines and i need to start a RPyC server inside one coroutine and i need to be able to send `yield` commands. 

I know that this application is not common. I want this because the coroutines are launched by an scheduler that controls a simulator engine and i need to continue simulation when all the coroutine are waiting for a simulation step.

For example:
Server/Simulator side:
``` python
@sim.coroutine 
def coroutine_A ( ... ):
    while True:
         yield ClasicServer.run()

@sim.coroutine 
def coroutine_B( ... ):
    yield WaitEvent('event')
    yield WaitEvent('another_event')
```
Client:
```python
conn = rpyc.classic.connect('localhost')
...
conn.execute("yield WaitEvent('event')")
conn.execute("yield WaitEvent('another_event')")
```
Before knowing RPyC project, i starting doing an ugly approach as is shown in https://github.com/andresdemski/pycocotb/blob/master/pycocotb/interactive.py

What do you think? Can i do this in a simple way or i need to change all RPyC architecture?

Thx!
Andres

**Comment by coldfix** [comment]
Hi, I'm sorry for the huge delay. What is your question excactly?

rpyc is capable of executing yields remotely. For example:

#### Server

```python
import rpyc.utils.server


class MyService(rpyc.Service):

    def exposed_bar(self):
        print("hello")
        yield "world"


rpyc.utils.server.ThreadedServer(MyService, port = 12345).start()
```

#### Client

```python
import rpyc
c = rpyc.connect("localhost", 12345)
print(list(c.root.bar()))
```

prints `hello` on the server side and `['world']` on the client.

**Comment by comrumino** [comment]
This sounds like a potential use case of [asynchronous](https://rpyc.readthedocs.io/en/latest/docs/async.html) operations.
