### ISSUE TITLE
Pipes and Named pipes in Windows very slow

### ISSUE THREAD

**Issue by pyscripter** [tomerfiliba/rpyc#306]
I was testing the relative speed of different transport protocols on windows.

sockets:
```
conn = rpyc.classic.connect("localhost")
>>> t = timeit.timeit(conn.ping, number=100)
>>> t
0.01832969809993301
```
pipes:
```
conn = rpyc.classic.connect_subproc(r"c:\python\vpython36\Scripts\rpyc_classic.py")
>>> t = timeit.timeit(conn.ping, number=100)
>>> t
10.053397062580675
```

Named pipes:
```
>>> np_client = NamedPipeStream.create_client("floop")
>>> conn = rpyc.classic.connect_stream(np_client)
>>> t = timeit.timeit(conn.ping, number=100)
>>> t
10.05315956866582
```

It appears that sockets about 500 times faster than pipes!  I find this quite surprising.  Local named pipes on windows are supposed to be as fast if not faster than sockets.  I know of the problem with the lack of poll and select for windows pipes, but there should be some scope for improvement (?).

By the way rpyc performance with sockets is very good.

##### Environment

- rpyc version (GitHub)
- python version 3.6
- operating system  Windows 10 with the latest updates

**Comment by pyscripter** [comment]
A downside of the above chance is that conn.serve_all will be running a tight loop consuming a lot of CPU resources.   An allternaive would be to keep the original function and change the default interval.

with
`
 def poll(self, timeout, interval = 0.01):
`
time drops from 10secs to 1sec for 100 pings and
with
`
 def poll(self, timeout, interval = 0.001):
`
time drops from 10secs to 0.38sec for 100 pings.   Much better that the original but still a lot worse than sockets.

**Comment by pyscripter** [comment]
I finally found a good solution that does not waste CPU time.
Add a safe-import:
`win32event = safe_import("win32event")
`
and change Win32PipeStream.poll to 
```
    def poll(self, timeout, interval = 0.001):
        """a poor man's version of select()"""
        timeout = Timeout(timeout)
        try:
            while True:
                if win32pipe.PeekNamedPipe(self.incoming, 0)[1] != 0:
                    return True
                if timeout.expired():
                    return False
                if timeout.timeleft() is None:
                    wait_time = win32event. INFINITE
                else:
                    wait_time = int(timeout.timeleft() * 1000)
                res = win32event.WaitForSingleObject(self.incoming, wait_time)
                if res == win32event.WAIT_TIMEOUT:
                    return False
        except TypeError:
            ex = sys.exc_info()[1]
            if not self.closed:
                raise
            raise EOFError(ex)
```
WaitForSingleObject is not recommended for file/pipe objects, however as Microsoft states in https://docs.microsoft.com/en-gb/windows/desktop/FileIO/synchronous-and-asynchronous-i-o

> An application can also wait on the file handle to synchronize the completion of an I/O operation, but doing so requires extreme caution. Each time an I/O operation is started, the operating system sets the file handle to the nonsignaled state. Each time an I/O operation is completed, the operating system sets the file handle to the signaled state. Therefore, if an application starts two I/O operations and waits on the file handle, there is no way to determine which operation is finished when the handle is set to the signaled state. If an application must perform multiple asynchronous I/O operations on a single file, it should wait on the event handle in the specific OVERLAPPED structure for each I/O operation, rather than on the common file handle.

and the code above still calls PeekNamedPipe after the wait is finished without a timeout.

with the above code
```
>>> import rpyc, timeit
>>> conn = rpyc.classic.connect_subproc(r"c:\python\vpython36\Scripts\rpyc_classic.py")
>>> t = timeit.timeit(conn.ping, number=100)
>>> t
0.009260206455207979
```

And still twice as fast as sockets and 1000 times faster than the current code.

**Comment by coldfix** [comment]
Great! I'm happy to accept PR on this. Is win32event commonly available on windows or does this introduce another dependency?

**Comment by pyscripter** [comment]
win32event is part of pywin32, same as win32file and win32pipe already used.  So no new dependency.  But wait.  Even the last version, introduces CPU overload.  So I am still looking for a better solution.

**Comment by pyscripter** [comment]
I have submitted a pull request #311 that properly implements asynchronous named pipes on Windows.

Features:
- Non blocking poll
- 1000 times faster than current implementation
- 40% faster than sockets.
- No new dependencies.  pywin32 still needed.  Modules of pywin32 imported with safe_import.


To test it.

Server:

```
import rpyc
from rpyc.core.stream import NamedPipeStream

def main():
    np_server = NamedPipeStream.create_server("floop")
    server = rpyc.classic.connect_stream(np_server)
    try:
        server.serve_all()
    finally:
        server.close()

if __name__ == '__main__':
    main()
```

Client:
```
import timeit
import rpyc
import rpyc.core.stream

np_client = rpyc.core.stream.NamedPipeStream.create_client("floop")
conn = rpyc.classic.connect_stream(np_client)

t = timeit.timeit(conn.ping, number=1000)
print(t)
conn.close()
```

**Comment by coldfix** [comment]
Many thanks for your work. I will close this assuming its done now.
