### ISSUE TITLE
class transmission

### ISSUE THREAD

**Issue by FalseProtagonist** [tomerfiliba/rpyc#309]
Hi,

Reading the documentation, rpyc is using brine to transmit only immutable primitives, is there any way to extend this?

Eg. if I want to transfer a dataframe, to I need to write (and call) a serializer/deserializer each side every time? If there any way to embed this cleanly?

Sorry if this is a stupid question.

**Comment by coldfix** [comment]
Not a stupid question at all. I think you got it exactly right. It is currently not supported to embed a custom de-/serializer, but if done cleanly, I would welcome PRs on this matter.

**Comment by FalseProtagonist** [comment]
Thanks for your quick answer!

**Comment by comrumino** [comment]
Closing this issue since the discussion here is exhausted and is being tracked in issue #350.
