### ISSUE TITLE
Suggestion: finer control over returning by value or by proxy

### ISSUE THREAD

**Issue by lurodrigo** [tomerfiliba/rpyc#310]
Hi! I would like to make a suggestion. [Theory of Operation](https://rpyc.readthedocs.io/en/latest/docs/theory.html) says simple, immutable objects are returned by value and everything else is returned by proxy. I think it would be really useful to have a way of forcing by-value return on a service method. Sometimes we return complex objects that don't actually interfere on anything server-side, so having proxy objects that do networking creates unnecessary overhead.

For example: I'm building right now a small distributed system for testing our company's algorithms (that do interact a lot with each other). I have services exposing methods that return numpy arrays or pandas objects. Since they are proxied, any operation with them involves networking and it quickly becomes difficult to reason about where the operations are actually taking place.

My workaround was to write wrappers calling `rpyc.utils.classic.obtain`. It's quite incovenient, not because of wrapping properly, but because it's client-side. Maybe we could have a decorator indicating that the method returns by value (or any other solution).

To be honest, I've been working with this package for only a few days, so maybe there's a better approach to that already available, or my understanding of rpyc's internal workings is wrong, but anyway I'd like to know what do you think about this. Thank you!

**Comment by comrumino** [comment]
Closing this issue since the discussion here is exhausted and is being tracked in issue #350.
