### ISSUE TITLE
When connect to the socket fails, the socket stays opened

### ISSUE THREAD

**Issue by ayalash** [tomerfiliba/rpyc#312]
`SocketStream._connect` method does not close the socket when the connect fails. Relevant code lines:
```
        s = socket.socket(family, socktype, proto)
        s.settimeout(timeout)
        s.connect(sockaddr)
```
https://github.com/tomerfiliba/rpyc/blob/master/rpyc/core/stream.py#L109-L111

This cause python warning to be emitted:
```
unclosed <socket.socket fd=24, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('...', 56927)>
```

**Comment by coldfix** [comment]
Hey, thanks for the report.

I have added some cleanup for this specific problem you describe, but I'm afraid there are many more places with similar issues, and it will be a mess to fix all of them.

**Comment by ayalash** [comment]
@coldfix ok, thanks for the fast fix :)
