### ISSUE TITLE
Suggested improvement in Connection serve_all

### ISSUE THREAD

**Issue by pyscripter** [tomerfiliba/rpyc#314]
Connection.serve_all has the following loop:

```python
        try:
            while True:
                self.serve(None)
        except (socket.error, select_error, IOError):
```

When the client side closes a connection, _handle_close will do the clean-up and set _closed to True.  However the serve_all loop will still be running and it will rely on exceptions raised to break out of the loop.  This is subject to delays due to timeouts.

I would suggest to replace the above with the following:

```python
        try:
            while not self.closed:
                self.serve(None)
        except (socket.error, select_error, IOError):
```
so that when closed the connection breaks out of the loop immediately and without exception.

**Comment by coldfix** [comment]
Thanks, makes sense.
