### ISSUE TITLE
isinstance not working over connection-boundaries

### ISSUE THREAD

**Issue by walterschneider** [tomerfiliba/rpyc#316]
isinstance() returns false if obj and class are not referenced over the same rpyc-connection.

I used a wrapper-script to create a new connection for each module to get them work simultanously when using from different threads at the client-side.

##### Environment

- rpyc 4.0.2
- python 3.6.7
- ubuntu 18.04 (bionic)

##### Minimal example

Server:

```bash
rpyc_classic.py
```

mod.py:

```python
class M:
    pass
```

client.py:

```python
import rpyc

# create connections
cn1=rpyc.classic.connect(host="localhost")
cn2=rpyc.classic.connect(host="localhost")

# import module at server-side
cn1.execute("import mod")

# get module per connection
rm1=cn1.modules.mod
rm2=cn2.modules.mod

# create instances of class 'M'
m1=rm1.M()
m2=rm2.M()


assert isinstance(m1, rm1.M)
assert isinstance(m2, rm2.M)

assert isinstance(m1, rm2.M) # fails
```

Client:
```bash
python3 client.py
```

**Comment by comrumino** [comment]
Marking this done. If there are other related issues in the next release. Feel free to reopen.
