### ISSUE TITLE
socket.gaierror: [Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by sschumm** [tomerfiliba/rpyc#319]
I am trying to work remotely on the Lego EV3 with ev3dev using RPyC as described in this tutorial:
https://ev3dev-lang.readthedocs.io/projects/python-ev3dev/en/stable/rpyc.html

Instead of a working connection the following error message shows up:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\svens\AppData\Local\conda\conda\envs\Python_RPyC_VEnv\lib\site-packages\rpyc\utils\classic.py", line 70, in connect
    return factory.connect(host, port, SlaveService, ipv6 = ipv6, keepalive = keepalive)
  File "C:\Users\svens\AppData\Local\conda\conda\envs\Python_RPyC_VEnv\lib\site-packages\rpyc\utils\factory.py", line 93, in connect
    s = SocketStream.connect(host, port, ipv6=ipv6, keepalive=keepalive)
  File "C:\Users\svens\AppData\Local\conda\conda\envs\Python_RPyC_VEnv\lib\site-packages\rpyc\core\stream.py", line 154, in connect
    return cls(cls._connect(host, port, **kwargs))
  File "C:\Users\svens\AppData\Local\conda\conda\envs\Python_RPyC_VEnv\lib\site-packages\rpyc\core\stream.py", line 109, in _connect
    socktype, proto)[0]
  File "C:\Users\svens\AppData\Local\conda\conda\envs\Python_RPyC_VEnv\lib\socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed
```

I also tried the New Style RPyC (https://rpyc.readthedocs.io/en/latest/tutorial/tut3.html) but it results in the same error message.
Any Ideas why this error pops up?

##### Environment
Server:
- rpyc version: 4.0.2
- python version: 3.5.3
- operating system: Linux ev3dev 4.14.80-ev3dev-2.3.1-ev3

Client:
- rpyc version: 4.0.2
- python version: 3.6.8
- operating system: Win10

##### Minimal example

Server:
```
#!/bin/bash
python3 `which rpyc_classic.py`
```

Client:

```
import rpyc
conn = rpyc.classic.connect('ev3dev')
```

**Comment by RichardHuenermann** [comment]
I have the same problem. Did you find a solution yet?

**Comment by sschumm** [comment]
Not yet. I am currently using the VS Code Extension for the EV3 which is far from ideal for my use case but its at least working.

**Comment by RichardHuenermann** [comment]
@sschumm exactly what I'm doing right now, but I'm not sure if I'm going to be able to achieve what I originally wanted via that approach. One thing I tried was entering the IP displayed on the brick instead of 'ev3dev' in the command line 
conn = rpyc.classic.connect( <robot IP> )
but that just yielded another error message..

**Comment by RichardHuenermann** [comment]
@sschumm hey again. I am now able to communicate with the EV3 via rpyc. 
I am using the latest ev3dev image "ev3dev-stretch-ev3-generic-2018-11-13".
On there, the version of rpyc is 3.3.0. After downgrading the rpyc version on the PC, the command works. Weirdly enough, only when using rpyc.classic.connect('ev3dev') and not by passing the robot's IP to the connect method, but as long as I have a working version, I don't mind.

**Comment by sschumm** [comment]
hey @RichardHuenermann  thank you so much, you're damn right: as long as it works!
