### ISSUE TITLE
The readthedocs website is outdated

### ISSUE THREAD

**Issue by pilcru** [tomerfiliba/rpyc#336]
At https://rpyc.readthedocs.io/en/latest/, the "news" banner point to the release of 4.0.2, and the changelog hasn't been updated to 4.1.0. This got me slightly confused when I was looking for info related to #330 and hit that page first before heading to github.

**Comment by comrumino** [comment]
Thanks for bringing this up. I'll look into updating the docs and will follow up here.

TODOs:

- [ ] Generate docs w/ sphinx
- [ ] Create release check list (i.e. double check for compatibility breaks, bump version, build & upload to PyPi, add the headlines to the change log & relevant details, generate docs with sphinx/mkdocs, tag/release on GitHub).
