### ISSUE TITLE
Issue template example is not working

### ISSUE THREAD

**Issue by pilcru** [tomerfiliba/rpyc#338]
The "minimal example" from the issue template does not run, and I don't think it ever has. The error it runs into is the same as #192. Is that intended?

I tested with Python 3, rpyc v4.1.0 and 4.0.2 with the same results.

Changing the `ListService` class in the template to this makes the example output `['hello', 'world']`:

```python
class ListService(rpyc.Service):
    def exposed_concat(self, lst):
        return [x for x in lst] + ['world']
```

**Comment by comrumino** [comment]
Thanks! Fixed the issue template. Support for type inheritance in a Netref runs into issues with lay-out conflicts---I put it under my personal todo list for now.

**Comment by pilcru** [comment]
Great, thank you for digging into that small collection of issues I posted last week! As others have said, I'm glad to see someone stepped up to maintain that project. I've been using rpyc for around 4 years as a way to "jailbreak" from an embedded IronPython, it's great to know it is still alive so many years after its inception.
