### ISSUE TITLE
Typo in netref.class_factory?

### ISSUE THREAD

**Issue by pilcru** [tomerfiliba/rpyc#339]
While investigating the other issue I posted today, I came across [this line](https://github.com/tomerfiliba/rpyc/blob/2f2a43e3538e4f6f21c0106a2f51a92ffcd623fb/rpyc/core/netref.py#L298) in `core.netref.py`. I'm almost certain this is a typo, but I wasn't able to link it to an actual bug. It might have no impact at all given how it's used in `protocol.netref_factory.py`.

Here is the code:
```python
if _module:
    if id_pack[0] != 0:
        ns["__class__"] = _module
    else:
        ns["__class__"] = getattr(_module, "__class__", None)
```
The test `id_pack[0] != 0` does not make sense since `id_pack[0]` is the `name_pack` string. Instead I think it should be 
```python
if _module:
    if id_pack[2] == 0:
       ...
```
Then if the object to be netref-ed is a class (`id_pack[2] == 0`), we can directly use it rather than finding its base class first.

**Comment by comrumino** [comment]
Ah good catch! It was supposed to be used in the else statement. Without it, some use cases could result in infinite recursion.
