### ISSUE TITLE
cannot run Windows gui application via rpyc 

### ISSUE THREAD

**Issue by iradization** [tomerfiliba/rpyc#341]
Hi, I'm using rpyc under python2.7.15 and my goal is to run a simple gui-based application (say c:\Windows\System32\notepad.exe)

on client side I do : 

```
conn = rpyc.classic.connect(remote_ip)
proc = conn.modules.subprocess.Popen(cmd, shell=True)
proc.communicate()
```
and on server side I simply run the c:\Python27\Scripts\rpyc_classic.py

However, it seems like the application got started but without any visible UI window on the remote/server machine, which is the notepad editor in my case.

I've also tried `conn.modules.os.system` which led to the same result ... 

Perhaps is there any way to config the rpyc client/server to support opening the gui window ?

Thanks

**Comment by comrumino** [comment]
It helps to break things down into smaller parts and isolate the exact issue. Using the path `c:\Windows\System32\notepad.exe` results in error
```
'c:\Windows\System32' is not recognized as an internal or external command,
operable program or batch file.
```
escaping the back slash fixes this issue (`"c:\\Windows\\System32\\notepad.exe"`). 

Here are the scripts I used.

**server.py:**
```
import subprocess
import rpyc
from rpyc.utils.server import OneShotServer


class NotepadService(rpyc.Service):
    def exposed_start_notepad(self):
        cmd = "c:\\Windows\\System32\\notepad.exe"
        proc = subprocess.Popen(cmd, shell=True)
        proc.communicate()


if __name__ == "__main__":
    rpyc.lib.setup_logger()
    server = OneShotServer(NotepadService, port=12345,
                           hostname="127.0.0.1")
    server.start()
```

**client.py:**
```
from __future__ import print_function
import rpyc


if __name__ == "__main__":
    c = rpyc.connect("127.0.0.1", 12345)
    print(c.root.start_notepad())
```
