### ISSUE TITLE
cannot access 'items' on server

### ISSUE THREAD

**Issue by ralfkundel** [tomerfiliba/rpyc#347]
Hi,
thanks to #272 i was able to access a dict on the client side. however, I'm unable to transfer a dict from client to server and access items().

**Server**:
```
class TimeService(Service):
    def exposed_get_a_dict(self, a):
        print(a)
        for k,v in a.items():
            print(k)
        return "asdf" 
s = ThreadedServer(TimeService, port=18871, protocol_config={'allow_public_attrs': True, 'sync_request_timeout': 10})
s.start()
```

**Client**:
```
conn = rpyc.connect('localhost', 18871)
foo = conn.root.get_a_dict({'yeah':42})

```
causes: AttributeError: cannot access 'items'

Is there another protocol_config which is required for that?

Used version: ubuntu 19.04, python3, current RPyC version

regards,
Ralf

**Comment by comrumino** [comment]
RPyC supports bidirectional communication and so `client.py` behaves as a server as well. Being so, it must be configured to `allow_public_attrs: True` when you would like `server.py` to access public attributes.
**server.py**
```
import rpyc


class TimeService(rpyc.Service):
    def exposed_get_a_dict(self, a):
        print(a)
        for k, v in a.items():
            print(k)
        return "asdf"


s = rpyc.utils.server.ThreadedServer(TimeService, port=18871, protocol_config={
                                     'allow_public_attrs': True, 'sync_request_timeout': 10})
s.start()
```

**client.py**
```
import rpyc
conn = rpyc.connect('localhost', 18871, config={'allow_public_attrs': True, 'sync_request_timeout': 10})
foo = conn.root.get_a_dict({'yeah': 42})
```
Hope that helps! If you run into anything else that is related, reopen the issue and I can help out.
