### ISSUE TITLE
rapid data streaming patch pull request

### ISSUE THREAD

**Issue by p5-vbnekit** [tomerfiliba/rpyc#353]
I tried to reduce the CPU usage and add a bit of zero-copy... That's what came out of it.

# Pull request
I tried to split these changes into [separate commits](https://github.com/tomerfiliba/rpyc/compare/master...p5-vbnekit:rapid_patch) so that it was easier to patch. But i'm not sure if these changes are portable. I could open a pull request, but I see that something is wrong with the Travis-CI. Therefore, I ask you to help me with testing, code-review, etc... We can merge it, i know. =)

# Fork
[rapid_pactch branch of my fork: https://github.com/p5-vbnekit/forks.rpyc/tree/rapid_patch](https://github.com/p5-vbnekit/forks.rpyc/tree/rapid_patch)

# Test sources
[raw.client.py.gz](https://github.com/tomerfiliba/rpyc/files/3712775/raw.client.py.gz)
[raw.server.py.gz](https://github.com/tomerfiliba/rpyc/files/3712777/raw.server.py.gz)

# Client test output
Size in bytes, Rate in megabytes.
```
normal mode testing
duration = 3.536377213000378, rate = 289.56187033317207, size = 1073741824
duration = 3.4768956789994263, rate = 294.51559509967365, size = 1073741824
duration = 3.5834064559985563, rate = 285.7616105161174, size = 1073741824
duration = 3.6162970469995344, rate = 283.1625794815776, size = 1073741824
duration = 3.5070690360007575, rate = 291.9817059454597, size = 1073741824
duration = 3.5336827020000783, rate = 289.78266764596947, size = 1073741824
duration = 3.493078114999662, rate = 293.15118823218734, size = 1073741824
duration = 3.5719206699995993, rate = 286.68049898211063, size = 1073741824
====================

no-compression mode testing
duration = 0.771746880000137, rate = 1326.8599155202521, size = 1073741824
duration = 0.815511136999703, rate = 1255.6542192266504, size = 1073741824
duration = 0.8134170849989459, rate = 1258.886761643723, size = 1073741824
duration = 0.8100284619995364, rate = 1264.1531107095668, size = 1073741824
duration = 0.8220064540000749, rate = 1245.732311488526, size = 1073741824
duration = 0.8575360779996117, rate = 1194.1188554873415, size = 1073741824
duration = 0.925070882, rate = 1106.9422029435361, size = 1073741824
duration = 0.7707344720001856, rate = 1328.6028291203165, size = 1073741824
====================

raw data mode testing
duration = 0.20740943400051037, rate = 4937.0946164265615, size = 1073741824
duration = 0.2318591910006944, rate = 4416.473617372939, size = 1073741824
duration = 0.2333542310007033, rate = 4388.178417030346, size = 1073741824
duration = 0.1913496449997183, rate = 5351.46015035203, size = 1073741824
duration = 0.238166461000219, rate = 4299.51385975819, size = 1073741824
duration = 0.23230152100040868, rate = 4408.064121104909, size = 1073741824
duration = 0.1920135050004319, rate = 5332.958220817315, size = 1073741824
duration = 0.2331290509991959, rate = 4392.416970819874, size = 1073741824
```

# `$ iperf -c localhost`
```
------------------------------------------------------------
Client connecting to localhost, TCP port 5001
TCP window size: 2.50 MByte (default)
------------------------------------------------------------
[  3] local 127.0.0.1 port 45062 connected with 127.0.0.1 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec  61.0 GBytes  52.4 Gbits/sec
```
52400 / 8 = 6550 MegaBytes per second

**Comment by p5-vbnekit** [comment]
Should i cancel next requests?

- [core.Channel.send upgrade: rate imporved ](https://github.com/tomerfiliba/rpyc/pull/351)
- [max_io_chunk + compression patch](https://github.com/tomerfiliba/rpyc/pull/352)

**Comment by p5-vbnekit** [comment]
Last commit additional info:

https://github.com/p5-vbnekit/forks.rpyc/commit/7ae570ca230a4394609e683c55d5983dd45c1bc6
This commit is ugly and implement `readinto` method for only SocketStream object. I hope we can make it better and i hope we can do same for other Stream classes.

**Comment by p5-vbnekit** [comment]
This commits was tested only on Debian GNU/Linux with python 3.7.
Because now i'm working on project with this platform. =)

**Comment by comrumino** [comment]
I'll close this issue here, and follow up with you on the PR. But, these look like good changes :)
