### ISSUE TITLE
Similar things to Python Multicall (xmlrpc)

### ISSUE THREAD

**Issue by csm10495** [tomerfiliba/rpyc#363]
Is there an equivalent to Python xmlrpc's Multicall (https://docs.python.org/3/library/xmlrpc.client.html#xmlrpc.client.MultiCall) ?

In particular is there a way that I can queue up some remote commands then 'send' them all to execute?

Optimally I'd also like to reference the result of the intermediate commands in future commands.

For instance in pseudocode:

send the following:
```
A + B 
(Result of A + B) + C
```

**Comment by comrumino** [comment]
Multicall or pipeline like support is not yet supported, but hope to add in the future. PRs are always welcome!

There might be some subtleties in design of a class with multicall-like behavior. RPyC behaves differently based on the object type of `A`, `B`, and `C`.  There are three types to keep in mind.

1. `brine.dumpable`, immutable objects that brine can serialize
2. `netref`, objects that cannot be serialized so a network reference is created to represent the object in another address space
3. local objects, objects that exist in the local address space

The aim would be to minimize network traffic when implementing a solution. The most complex aspect to consider is how RPyC over RPyC (chained connections) would be handled. I'll use this issue to track support of a multicall-like feature.

A flexible solution that users would find intuitive is likely more complex then implementing a solution specific to your use case. Let me know if I can clarify or expand on anything!

**Comment by comrumino** [comment]
Tracking at #326
