### ISSUE TITLE
Question: how to get original object from proxy ?

### ISSUE THREAD

**Issue by shazz** [tomerfiliba/rpyc#368]
I'm writing some unit tests to check that my remote objects behave like local objects.
and as all objects are proxified, common == or equals methods usually fail because the object types are different.
ex:
````
<class 'numpy.dtype'>
<netref class 'rpyc.core.netref.numpy.dtype'>
````

for example, comparing a local ndarray with a remote ndarray using `tolist()` or `(a==b).all()` will fail.

Printing them look ok:
````
local: [dtype('int64'), dtype('int64')]
remote: [dtype('int64'), dtype('int64')]
````
But comparing both returns False as the types differ.

So is it possible to get the real class from the netref class ?

##### Environment

- rpyc version 4.1.2
- python version 3.7
- operating system Ubuntu 18.04

**Comment by comrumino** [comment]
The 4.1.3 release may have resolved some of the issues that you experienced. Numpy can be a little trickier sometimes.
`client.py`
```python
#!/usr/bin/env python
import rpyc
import numpy


conn = rpyc.utils.factory.unix_connect('/tmp/session')
_a=conn.root.exposed_the_real_answer_though
_b=[numpy.dtype('int64')]
print('_a == _b', rpyc.classic.obtain(_a) == _b)
```
`server.py`
```python
#!/usr/bin/env python
import os
import rpyc
from rpyc.utils.server import ThreadedServer
import numpy


class MyService(rpyc.Service):
    exposed_the_real_answer_though = [numpy.dtype('int64')]


if __name__ == "__main__":
    session_path = '/tmp/session'
    if os.path.exists(session_path):
        os.remove(session_path)
    tserver = ThreadedServer(MyService,
                             socket_path=session_path,
                             protocol_config={ "allow_pickle": True})
    tserver.listener.settimeout(0.5)
    tserver.start()
```

**Comment by comrumino** [comment]
Feel free to reopen if you have any other questions
