### ISSUE TITLE
Question: What are best practicies to transfer files(upload/download) by using Custom Service  

### ISSUE THREAD

**Issue by amorozenko-ua** [tomerfiliba/rpyc#372]
Hi!
For Classic Service upload/download procedures can be used by rpyc.utils.classic calls.
But how I can do binary file transfers client <-> remote by running my Custom Service.
What is the best approach for your point of view to do such things?

Unfortunately current documentation has lack information about this thus need your support here.

Thanks in advance for your reply.

**Comment by comrumino** [comment]
No worries. I'm always glad to answer any questions.

Any brineable type such as byte or string would be the best practice. For many use cases, simply pass file content as a parameter or read the file within the remote address space and it will be returned. Of course, if the file is large enough you will run into issues. Large file transfer speeds are limited by TCP for now. Future data transfer optimizations are tracked by #326
