### ISSUE TITLE
How do I expose all global variables like Classic Server?

### ISSUE THREAD

**Issue by MehdiSaffar** [tomerfiliba/rpyc#386]
Hi everyone,

First of all, I would like to thank all the people that put effort into
contributing to this library. I am very glad to have found the closest solution
to what I want to do.

I would like to have a server that keeps (among other things) a MongoDB
connection alive. This server will be like a daemon. It will be used to grab
the current active connection by a CLI tool that gets invoked frequently.

By reading the docs and playing around with the examples, this is what I came up with:

```python
import pymongo
import rpyc
import rpyc.utils.server

# DB connection I want to keep alive and share
mongo = pymongo.MongoClient(MONGODB_URI)

class MyService(rpyc.core.SlaveService):
    def get_mongo(self):
        return mongo

server = rpyc.utils.server.ThreadedServer(MyService, port=3000)
server.start()
```

I needed to expose `mongo` global variable somehow but I couldn't and that was
the only way. It does what I want becaus e I am able to do this in my client
even if it the client reloads multiple times:

```python
s = rpyc.classic.connect('localhost', port=3000)
db = s.root.get_mongo()

print(db.my_database_name.my_collection.find_one({'email': 'xxx@gmail.com'}))
```

Is there a shorter way around this? Because otherwise I would have to add a method in `MyService` for every global variable I want to expose.

Ideally I would like the client to be able to reach into server-side global variables like:

```python
server.root.my_var_1.do_something()
print(server.root.my_string_2)
...
```

Is this possible? Thank you

##### Environment

- rpyc version: rpyc 4.1.5
- python version: Python 3.8.1
- operating system: Ubuntu 19.10

**Comment by comrumino** [comment]
Using so many globals seems convienent, but also like a poor design choice. Even so, 
```
t = ThreadedServer(
    MyService,
    port=18861,
    protocol_config={'allow_all_attrs': True}
)
```
The above is how you can configure the server to allow all attrs and use the built-in `globals()` might achieve what you are looking for here.
