### ISSUE TITLE
add background reactor thread

### ISSUE THREAD

**Issue by tomerfiliba** [tomerfiliba/rpyc#84]
this will solve all thread-related issues once and for all. no more BgServingThread, etc. it's time to kill threading issues

**Comment by coldfix** [comment]
As far as I understand the issue, a background reactor thread on its own is not an easy solution to solve the real architectural issues in rpyc which is: how to run requests and async replies without blocking/deadlocking etc other tasks. IMO the only solutions are:
- asyncio, but asyncio support would drag through the entire code base and doesn't work with rpyc's seemless function call style
- greenlets (gevent), which is probably a close-to-perfect match! In fact, depending on gevent could simplify rpyc's internal logic by a lot! Problem: not sure how it works with multi-threading/forking servers

I'm going to close this for now and focus work on gevent for 4.0 instead. If needed, can be reopened for further discussions.
